PersonalSite/Controllers/LoginAccountController.cs
using PersonalSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace PersonalSite.Controllers
{
    public class LoginAccountController : Controller
    {
        private IUserDataAccess dataAccess;
        private UserMemberProvider provider = (UserMemberProvider)Membership.Provider;

        public LoginAccountController()
            :this(new SqlUserDataAccess())
        {
        }

        public LoginAccountController(IUserDataAccess dataAccess)
        {
            this.dataAccess = dataAccess;
        }

        public ActionResult Login()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult LogOn(string userName, string password, string returnUrl)
        {
            if (!ValidateLogOn(userName, password))
            {
                return View("Login");
            }

            var user = dataAccess.GetUserByName(userName);

            FormsAuthentication.SetAuthCookie(user.UserName, false);

            if (!String.IsNullOrEmpty(returnUrl) && returnUrl != "/")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        private bool ValidateLogOn(string userName, string password)
        {
            if (String.IsNullOrEmpty(userName))
            {
                ModelState.AddModelError("Login", "You must specify a username.");
            }
            else if (String.IsNullOrEmpty(password))
            {
                ModelState.AddModelError("Login", "You must specify a password.");
            }
            else if (!provider.ValidateUser(userName, password))
            {
                ModelState.AddModelError("Login", "The username or password provided is incorrect.");
            }
            return ModelState.IsValid;
        }

    }
}

PersonalSite/Views/LoginAccount/Login.cshtml
@model PersonalSite.Views.LoginViewModel
<div class="signinbox">
<h2 class="pageHeaders">
    Log In
</h2>
 
    @using (Html.BeginForm("LogOn", "LoginAccount", FormMethod.Post)) {
        <div id="login" class="midContentContainer">
		    <div id="loginUser">
                @Html.TextBoxFor(m => m.UserName, new { @id = "loginUsernameText", @class = "shortTextArea", @placeholder = "Username" })
		    </div>
		    <div id="loginPassword">
			    @Html.PasswordFor(m => m.Password, new { @id = "loginPasswordText", @class="shortTextArea", @placeholder = "Password"})
		    </div>
            <div id="loginSubmit">
                <input type="submit" class="bigSubmit" value="Submit"/>
            </div>
            @if (!ViewData.ModelState.IsValid)
            {
                <div id="errorMessage">
                    @Html.ValidationMessage("Login")
                </div>
            }
        </div>
        
    }
 
</div>
<script type="text/javascript">
    $(document).ready(function () {
        //$("#loginUsernameText").val = "Username";
        //$("#loginPasswordText").val = "Password";
    });
</script>